CREATE TABLE TEACHERS(
TEACHER_ID INT PRIMARY KEY,
AGE INT 
)

CREATE TABLE SUBJECT(
TEACHER_ID INT,
SUBJECT VARCHAR(20)
CONSTRAINT T1 FOREIGN KEY(TEACHER_ID)
REFERENCES TEACHERS(TEACHER_ID))

INSERT INTO TEACHERS VALUES(1,30)
INSERT INTO TEACHERS VALUES(2,31)
INSERT INTO TEACHERS VALUES(3,32)

INSERT INTO SUBJECT VALUES(1,'MATHS')
INSERT INTO SUBJECT VALUES(1,'PT')
INSERT INTO SUBJECT VALUES(2,'CHEMISTRY')
INSERT INTO SUBJECT VALUES(2,'BIOLOGY')
INSERT INTO SUBJECT VALUES(3,'PHYSICS')

SELECT * FROM TEACHERS

SELECT * FROM SUBJECT